# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Online Movies' do

    use_frameworks!

  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Cosmos'
  pod 'SDWebImage', '~> 4.0'
  pod 'DropDown'
  pod 'WCLShineButton'
  pod 'Dropdowns'
  pod 'ExpandableCell'
  pod 'YouTubePlayer'
  
  

end
